### ISSUE TITLE
🐞[Bug]: The GUI is invisible

### ISSUE THREAD

**Issue by the-liquid-metal** [David-Maisonave/MediaFileDuplicateFinder#4]
### Please enter a clear and concise description of the bug.

The GUI is invisible. Just the icon in taskbar.

### What Operating System (OS)?

windows 10

### What version of MediaFileDuplicateFinder?

Version 1.5

### Where did you download MediaFileDuplicateFinder from?

github

**Comment by David-Maisonave** [comment]
Thank you very much for reporting this issue.

This issue if very strange. I always upload the release files to Github from my local repository. I just tested the local repository files, and they work, but when I download the files from Github, they fail!

I usually use a script to upload the files automatically, so I thought something failed in the script, so I manually updated the Github files, and the **win-x64_Ver1.5.zip** works now, but the **win-x64_Ver1.5_Setup.msi** still fails. I'm getting an **Access is denied** error. 
This might be some anti-virus settings on my computer triggering the error, but until I'm certain, I'm going to remove  **MediaFileDuplicateFinder_win-x64_Ver1.5_Setup.msi** from the release.

For now, please use MediaFileDuplicateFinder_win-x64_Ver1.5.zip.

Thanks

**Comment by the-liquid-metal** [comment]
Solved. Missing required .net runtime. Please inform the user to install it.
