### ISSUE TITLE
[Enhancement]: JPEG auto-rotation

### ISSUE THREAD

**Issue by fonitzu** [David-Maisonave/MediaFileDuplicateFinder#8]
### A clear and concise description of the feature or enhancement you'd like to see in MediaFileDuplicateFinder

Please consider image rotation when comparing.

Issue:
I have two JPEG images: one original and the original sent through whatsapp.
The whatsapp image has a lower resolution and size.
Interestingly enough, they were not detected as duplicate,
even if they were 100% identical when compared visually using IrfanView.
Lowering the detection threshold to 50% has revealed that the matching score was around 70%,
but: one image was shown in thumbnail rotated with 180 degrees (head down).

It's clear that IrfanView used the auto-rotation flag from JPEG,
showing both images "correctly".

Would be possible to add a setting flag similar to "try to match images rotated with 180 degrees"?
Or even make it configurable, like
- 90 degrees rotation,
- 180 degrees rotation,
- 270 degrees rotation,
- vertical flip.

Horizontal flip exists already.
BTW, it is obvious that the processing time will increase when such options are activated.

Thank you!

### Is it OS specific?

Any

### Where did you download MediaFileDuplicateFinder from?

github

### Snapshots / Images

![20230405_183904](https://github.com/user-attachments/assets/e3e71ae9-eca5-4cce-a4cc-9425c618cfda)
![20230405_145925002](https://github.com/user-attachments/assets/0d13e6a3-8264-4db9-accb-86c0b4d60b30)

**Comment by David-Maisonave** [comment]
You need a ffmpeg or ffprobe command line option that would help perform auto-rotation while in the process of getting a hash result.
I looked in the following link, and I couldn't find a command line option that would help:
https://ffmpeg.org/documentation.html

If you could find such an option, all you have to do is add the argument to **Settings->Misc->[Custom FF Arguments]** field.

Sorry, but if ffmpeg or ffprobe doesn't have support for this, it's not practical to add this enhancement to MediaFileDuplicateFinder.
